name: Hadolint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: hadolint/hadolint:v2.12.1-beta-debian
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Linter
        run: |
          hadolint Dockerfile
