name: Hadolint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: docker://hadolint/hadolint
    steps:
         - name: Log the node version
           run: |
             node -v
             cat /etc/os-release
