name: Hadolint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: hadolint/hadolint:latest
    steps:
         - name: Linter
           run: |
             hadolint Dockerfile
